# Generated by Django 2.2.7 on 2019-11-07 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidaOleo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('oleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='estoque.Oleo')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oleos', to='estoque.Projeto')),
            ],
            options={
                'verbose_name': 'Saída de Óleo',
            },
        ),
        migrations.CreateModel(
            name='EntradaOleo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('oleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='estoque.Oleo')),
            ],
            options={
                'verbose_name': 'Entrada de Óleo',
            },
        ),
    ]
