# Generated by Django 2.2.7 on 2019-11-07 23:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_entradaoleo_saidaoleo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
            },
        ),
        migrations.AddField(
            model_name='entradaoleo',
            name='data_entrada',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradaoleo',
            name='numero_notafiscal',
            field=models.CharField(default='abc', max_length=200, verbose_name='Número da nota fiscal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saidaoleo',
            name='data_saida',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de saída'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saidaoleo',
            name='resposavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='oleos', to='estoque.Responsavel'),
            preserve_default=False,
        ),
    ]
