# Generated by Django 2.2.7 on 2019-11-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_auto_20191107_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=250)),
                ('numero', models.CharField(max_length=250, verbose_name='número')),
            ],
        ),
    ]
